# Generated by Django 4.2.7 on 2026-01-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_task_status_alter_taskassignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
