# Generated by Django 4.2.7 on 2026-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_taskassignment_notes_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="performance_rating",
            field=models.IntegerField(
                blank=True,
                help_text="PM's rating of employee performance on this task (e.g. 1-5)",
                null=True,
            ),
        ),
    ]
