# Generated by Django 4.2.7 on 2026-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_taskassignment_performance_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="communication_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="performance_comments",
            field=models.TextField(
                blank=True, help_text="Detailed PM feedback", null=True
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="quality_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="technical_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="timeliness_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="performance_rating",
            field=models.FloatField(
                blank=True,
                help_text="Overall PM rating of employee performance (calculated average)",
                null=True,
            ),
        ),
    ]
