# Generated by Django 5.1.4 on 2026-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_taskassignment_communication_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_UPLOADED", "Not Uploaded"),
                    ("PROCESSING", "Processing"),
                    ("READY", "Ready"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="NOT_UPLOADED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("UNASSIGNED", "Unassigned"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("BLOCKED", "Blocked"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("BLOCKED", "Blocked"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="ASSIGNED",
                max_length=20,
            ),
        ),
    ]
