# Generated by Django 5.1.4 on 2026-05-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_cv_status_alter_project_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="team",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
