# Generated by Django 5.1.4 on 2026-05-31 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_employee_role_employee_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complexity_level",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                blank=True,
                help_text="e.g., bugfix, feature, research, documentation",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TaskSkillEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                (
                    "required_level",
                    models.IntegerField(default=3, help_text="1-5 scale"),
                ),
                (
                    "achieved_level",
                    models.IntegerField(default=3, help_text="1-5 scale"),
                ),
                ("pm_comment", models.TextField(blank=True, null=True)),
                ("evidence", models.TextField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_evaluations",
                        to="core.taskassignment",
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "skill_name")},
            },
        ),
    ]
