# Generated by Antigravity

from django.db import migrations

def enable_rls(apps, schema_editor):
    # Only execute on PostgreSQL
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Get all tables in the public schema
            cursor.execute("""
                SELECT tablename 
                FROM pg_tables 
                WHERE schemaname = 'public';
            """)
            tables = cursor.fetchall()
            for (table,) in tables:
                cursor.execute(f'ALTER TABLE "public"."{table}" ENABLE ROW LEVEL SECURITY;')

def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT tablename 
                FROM pg_tables 
                WHERE schemaname = 'public';
            """)
            tables = cursor.fetchall()
            for (table,) in tables:
                cursor.execute(f'ALTER TABLE "public"."{table}" DISABLE ROW LEVEL SECURITY;')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task_complexity_level_task_task_type_and_more'),
    ]

    operations = [
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
