name: ITAS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        cd itas-backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django
    - name: Run Tests
      run: |
        cd itas-backend
        pytest

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - name: Install dependencies
      run: |
        cd itas-frontend
        npm ci
    - name: Build
      run: |
        cd itas-frontend
        npm run build
